name: Build Minecraft Mod

on:
  push:
    branches:
      - main  # 监控推送到 main 分支的代码
  pull_request:
    branches:
      - main  # 监控针对 main 分支的拉取请求

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境进行构建

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'  # Minecraft 1.12.2 需要 JDK 8
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

       
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
                
    - name: get wrapper
      run: | 
         ./gradlew wrapper
        
    - name: Build the mod
      run: | 
        ./gradlew build   # 运行 Gradle 构建命令

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: minecraft-mod
        path: build/libs/*.jar  # 上传生成的 JAR 文件
